services:
    postgres:
        image: postgres:16.1-alpine3.18
        command:
            - "postgres"
            - "-c"
            - "config_file=/etc/postgresql.conf"
        volumes:
            - ./docker/db:/var/lib/postgresql/data
            - ./docker/postgres/conf/postgresql.conf:/etc/postgresql.conf:ro
            - ./docker/postgres/conf/pg_hba.conf:/etc/pg_hba.conf:ro
        environment:
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
    nginx:
        build:
            context: ./docker/nginx
        depends_on:
            - php
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./:/var/www/php
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d/:ro
            - ./docker/certbot/www/:/var/www/certbot/:ro
            - ./docker/nginx/ssl/:/etc/nginx/ssl/:ro
            - ./docker/certbot/conf/:/etc/nginx/letsencrypt/:ro
    php:
        build:
            context: ./docker/php
        depends_on:
            - postgres
        volumes:
            - ./:/var/www/php
            - ./docker/php/php.ini:/usr/local/etc/php/php.ini
            - ./docker/php/www.conf.default:/usr/local/etc/php-fpm.d/www.conf.default
    certbot:
        image: certbot/certbot:latest
        volumes:
            - ./docker/certbot/www/:/var/www/certbot/:rw
            - ./docker/certbot/conf/:/etc/letsencrypt/:rw
    node:
        image: node:18.20.4-alpine3.20
        working_dir: /var/www/mini-app
        volumes:
            - ./:/var/www/mini-app
    adminer:
        image: adminer
        depends_on:
            - postgres
        ports:
           - "8080:8080"                
